name: Run_APEX_Test_On_Develop

on:
  pull_request:
    branches: [develop]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    - name: 'Populate auth file with SFDX_URL secret of integration org'
      shell: bash
      run: |
            echo ${{ secrets.SFDC_DEV_AUTH_URL}} > ./SFDC_DEV_AUTH_URL.txt
    - name: Authenticate with Salesforce
      run: |
         sfdx auth:sfdxurl:store -f ./SFDC_DEV_AUTH_URL.txt -s -a integration
    - name: Run Apex tests
      run: sfdx force:apex:test:run -l RunLocalTests -w 10
