name: Run_APEX_Test_On_Develop

on:
  pull_request:
    branches: [develop]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    - name: prepare_authenticate
      shell: bash
      run: |
        echo ${{ secrets.SFDC_DEV_AUTH_URL }} > ./SFDC_DEV_AUTH_URL.txt
    - name: authenticate_to_production
      # original repo forcedotcom/salesforcedx-actions@master
      uses: marcelblijleven/salesforcedx-actions@master
      with:
        args: force:auth:sfdxurl:store --sfdx-url-file=./SFDC_DEV_AUTH_URL.txt --alias=develop
    - name: Run Apex tests
      run: sfdx force:apex:test:run -l RunLocalTests -w 10
