# This is a basic workflow to help you get started with Actions
name: Auto_Deploy_To_Production_Org
on:
  pull_request:
    branches: [main]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_to_production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: prepare_deploy_data
      shell: bash
      run: |
        echo ${{ secrets.SFDC_PRO_AUTH_URL }} > ./SFDC_PRO_AUTH_URL.txt
        echo "files_to_deploy=$(git --no-pager diff --name-only --diff-filter=d origin/${{ github.base_ref }} -- force-app | tr '\n' ',' | sed 's/,/, /g' | sed 's/\(.*\),/\1 /')" >> $GITHUB_ENV
    - name: authenticate_to_production
      # original repo forcedotcom/salesforcedx-actions@master
      uses: marcelblijleven/salesforcedx-actions@master
      with:
        args: force:auth:sfdxurl:store --sfdx-url-file=./SFDC_PRO_AUTH_URL.txt --alias=main
    - name: deploy_files
      # original repo forcedotcom/salesforcedx-actions@master
      uses: marcelblijleven/salesforcedx-actions@master
      with:
        args: force:source:deploy -c -p force-app -u ${{ secrets.SFDC_PRO_USERNAME }} -l RunLocalTests

    - run: $([ $? -eq 0 ]  || exit 1)
